services:
  - type: web
    runtime: python
    name: pvt-tmy-api
    branch: main
    rootDir: pvt-tmy-api
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    autoDeployTrigger: checksPass
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.11
